In [ ]:
"""
改进id3_learn.ipynb中的不足,在python的pandas和numpy中找寻相关的api简化一些函数。
"""

In [ ]:
"""
计算初始熵值的改进方法，pandas实现。耗时耗力。
"""

In [5]:
import pandas as pd
import numpy as np
import math

In [6]:
dataset = np.array([(0,2,0,0,0), (0,2,0,1,0), (1,2,0,0,1), (2,1,0,0,1), 
                   (2,0,1,0,1), (2,0,1,1,0), (1,0,1,1,1), (0,1,0,0,0), 
                   (0,0,1,0,1), (2,1,1,0,1), (0,1,1,1,1), (1,1,0,1,1), 
                   (1,2,1,0,1), (2,1,0,1,0)])

In [13]:
#dataset[:,0]

array([0, 0, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 2])

In [12]:
#按列循环
k = []
for i in range(0,5):
    k.append(dataset[:,i])
k

[array([0, 0, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 2]),
 array([2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1]),
 array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1]),
 array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])]

In [16]:
value = 1
[m, n] = dataset.shape
retDataSet = []
for j in dataset[:,0]:
    if j == value:
        retDataSet.append(j)
retDataSet

[1, 1, 1, 1]

In [23]:
#求熵解决方案,完美解决问题
[m,n] = dataset.shape
label = dataset[:,n-1]
label_del = np.unique(label)
entropy = 0
for i in label_del:
    condition = (label == i)
    a = np.extract(condition, label)
    b = len(a)/len(label)
    entropy = entropy - b*math.log(b,2)

In [28]:
#封装上述函数,参数是一个numpy的一维数组,这里考虑一下是否可以传入一维数组无法做到看来要修改
def calEntropy(label):
    label_del = np.unique(label)
    entropy = 0
    for i in label_del:
        condition = (label == i)
        a = np.extract(condition, label)
        b = len(a)/len(label)
        entropy = entropy - b*math.log(b,2)
    return entropy

In [37]:
#找最佳特征,算出所有特征的信息熵
[m,n] = dataset.shape
newentropytemp = 0
newentropy = []
for j in range(0,n-1):#对所有的列进行循环
    k = np.unique(dataset[:,j])
    for i in k:
        condition = (dataset[:,j] == i)
        a = np.extract(condition, dataset[:,n-1])#a是一个array对象，是满足第j列各属性值时最后一列
        prob = len(a)/m
        newentropytemp = newentropytemp - prob*calEntropy(a)#需要定义求解一个一维数组的熵值
    newentropy.append(newentropytemp)
#计算信息增益最大的情况
basentropy = calEntropy(dataset[:,n-1])#数字和列表之间不能计算，把newentropy转化为numpy数组
newentropy = np.array(newentropy)#下面数组和数字之间可以进行计算。
infoGain = basentropy - newentropy

#求得最佳分裂特征的列编号

In [38]:
basentropy - newentropy

array([1.6338221 , 2.54488549, 3.33333595, 4.22549488])

In [ ]:
#分离数据
def splitDataSet(dataSet, axis, value):
    retDataSet = []
    for featVec in dataSet:
        if featVec[axis] == value:
            reducedFeatVec = featVec[:axis]
            reducedFeatVec.extend(featVec[axis+1:])
            retDataSet.append(reducedFeatVec)
     
    return retDataSet